name: aws-integration
displayName: AWS EC2 Integration
description: New Relic install recipe for AWS EC2 instances
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Ec2
  - Elastic
  - Compute
  - Aws
  - Cloud

imdsMatch: /latest/meta-data/instance-id

preInstall:
  info: |2
      This installation will provide additional instrumentation for Linux instances virtualized via AWS EC2.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 0

postInstall:
  info: |2
      ⚙️  The AWS integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
