name: azure-integration
displayName: Microsoft Azure Integration
description: New Relic install recipe for Azure virtual machine instances
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Virtual
  - Machine
  - Azure
  - Cloud

imdsMatch: /metadata/instance/compute/vmId

preInstall:
  info: |2
      This installation will provide additional instrumentation for Linux instances virtualized via Azure.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 0

postInstall:
  info: |2
      ⚙️  The Azure integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-vms-monitoring-integration/
