name: gcp-integration
displayName: Google Cloud Platform Integration
description: New Relic install recipe for GCP Compute Engine instances
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Compute
  - Engine
  - Gcp
  - Cloud

imdsMatch: /computeMetadata/v1/instance/id

preInstall:
  info: |2
      This installation will provide additional instrumentation for Linux instances virtualized via GCP Compute Engine.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 0

postInstall:
  info: |2
      ⚙️  The GCP integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-compute-engine-monitoring-integration/
